controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
app_stripe_success:
    path: /stripe/success/{id}
    controller: App\Controller\StripeController::successAction
app_stripe_cancel:
    path: /stripe/cancel/{id}
    controller: App\Controller\StripeController::cancelToRecap
app_stripe_cancel_to_profil:
    path: /stripe/profil/cancel/{id}
    controller: App\Controller\StripeController::cancelToProfil